exclude: '(^|/)(\.venv|venv|node_modules|__pycache__|migrations|static|templates|\.git|\.github|\.langgraph_api|media)(/|$)|^tests(/|$)|^unit_tests(/|$)|\.(env(\.example)?|gitignore)$|LICENSE|README\.md|langgraph\.json|uv\.lock'

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi]
